# Generated by Django 3.2.9 on 2022-10-14 13:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FirstLayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'First layer categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_ordered', models.DateTimeField(auto_now=True, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('order_token', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=1)),
                ('image_1', models.ImageField(upload_to='product-image')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product-image')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product-image')),
                ('description', models.TextField(max_length=500)),
                ('additional_info', models.TextField(max_length=500)),
                ('shipping', models.CharField(max_length=1000)),
                ('tag', models.CharField(max_length=800)),
                ('rating', models.IntegerField(default=0)),
                ('liked', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('date_Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SecondLayerSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Second layer categories',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=1000)),
                ('street', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('State', models.CharField(max_length=1000)),
                ('zip_code', models.CharField(max_length=1000)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('apartment_address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('private', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='shop.Product')),
            ],
        ),
    ]
