# Generated by Django 3.2.9 on 2022-10-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
