# Generated by Django 3.2.9 on 2022-10-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20221021_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='shop.product'),
        ),
    ]
