# Generated by Django 3.2.9 on 2022-10-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20221021_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_completed',
        ),
    ]
