# Generated by Django 3.2.9 on 2023-06-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_orderproduct_order_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='university',
            field=models.CharField(default='Abuad University', max_length=800),
        ),
    ]
