# Generated by Django 3.2.9 on 2023-06-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20230617_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='university',
        ),
    ]
