# Generated by Django 3.2.9 on 2023-07-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(choices=[('thrift', 'thrift'), ('brand new', 'brand new'), ('first grade', 'first grade'), ('second grade', 'second grade')], default='thrift', max_length=20),
        ),
    ]
