# Generated by Django 3.2.9 on 2023-07-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_transit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_token',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
