# Generated by Django 3.2.9 on 2023-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='user_address',
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, default='university', max_length=100, null=True),
        ),
    ]
