# Generated by Django 3.2.9 on 2023-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor_role',
            field=models.BooleanField(default=False),
        ),
    ]
